# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMvGOUtD-IfPzVcqdZav0o09yUMz29-W
"""

import streamlit as st
import random

def confess_love():
    opening = [
        "Toy có chiện này muốn nói với cậu...",
        "Cậu có một phút không? Quan trọng lắm!",
        "Ơ này, cậu rảnh không? Toy có điều này muốn thú nhận..."
    ]
    teasing = [
        "Đoán đc toy sẽ nói gì chưa? 🤭",
        "Cậu nghĩ toy sẽ nói thích cậu hả? 😆",
        "Hmmm, để toy suy nghĩ chút đã... 🤔",
        "Thôi ngại quá, không nói nữa đâu! 🙈"
    ]
    suspense = [
        "Kakaka k nói đâu lêu lêu! 🤪",
        "Toy có nên nói không ta? 🤔",
        "Nếu cậu đoán đúng toy sẽ nói thật! 😏",
        "Thật ra... thật ra thì..."
    ]
    climax = [
        "Nói chứ, h cậu chọn YES hay NO? 💖",
        "Toy thả thính nhiều rồi, giờ cậu quyết định đi! 😝",
        "Chọn YES thì cậu sẽ có một người thương siêu cute, chọn NO thì... toy sẽ buồn lắm đó! 😢"
    ]

    messages = [random.choice(opening), random.choice(teasing), random.choice(suspense), random.choice(climax)]

    st.title("💘 1 chút tên tên trong ngày 💘")
    for line in messages:
        st.write(line)

    reply = st.radio("Cậu chọn gì nè?", ["yes", "no"], index=1)
    if st.button("Gửi câu trả lời! 💌"):
        if reply == "yes":
            st.success("Yayyy! Cậu là định mệnh của toy rồi đó! 💘")
        else:
            st.error("Không sao, toy kiên nhẫn lắm, đợi đến khi nào cậu chọn YES thôi! 😎")

if __name__ == "__main__":
    confess_love()